### PR TITLE
Remove some strange hugs

### PR DESCRIPTION
**Pull request by RhinosF1**
Per user feedback

### CODE REVIEW

**Comment by RhinosF1** [comment]
See -dev channrl

**Comment by RhinosF1** [comment]
Why is the more obvious button close

**Comment by RhinosF1** [comment]
Bump

**Comment by linuxdaemon** [comment]
I'll admit these are odd but not inherently bad. I don't see a reason to remove them at this time.

**Comment by Techman** [comment]
I'll reference what I wrote in the IRC channel last year:

---
>2019-12-01 19:51:12 \<Techman\> I'm not sure about this, I guess some people might be offended by the lines but I think of gonzo as more of a project now than something specific to Snoonet. I'm not sure if user feedback from one particular channel on IRC should affect the project globally

**Pull request closed without merging**
